Repository EWHA-LUX/ONCE-FE, pull requests merged in 2024-04, with the labels that each got.

#57 [Feature] 카드 등록 서버 연결
  lib/src/screens/login/signup3.dart
  lib/src/screens/login/signup4.dart
Labels: feature, 지민

#58 [Fix] 월별 혜택 조회 상단 그래프 오류 수정
  lib/src/screens/mypage/monthly_benefit.dart
Labels: feature, 지민

#59 [Feature] 내 정보 수정하기 서버 연결
  assets/images/icons/edit_check_icon.svg
  lib/src/screens/mypage/user_edit.dart
Labels: feature, 지민

#60 [Feature] 마이월렛 카드 혜택 요약 서버 연결
  lib/src/screens/mywallet/card_item.dart
  lib/src/screens/mywallet/mywallet.dart
Labels: feature, 지민

#63 [Fix & Feature] 오버 플로우 해결 & 일부 페이지 수정
  lib/src/screens/login/signup1.dart
  lib/src/screens/login/signup2.dart
  lib/src/screens/login/signup3.dart
  lib/src/screens/login/signup4.dart
  lib/src/screens/mypage/user_edit.dart
  lib/src/screens/mywallet/card_item.dart
  lib/src/screens/mywallet/mywallet.dart
Labels: feature, 해원, fix

#66 [ Fix] 알림 RangeError 해결
  lib/src/screens/home/notification.dart
Labels: 해원, fix

#68 [Feature] 카드 추천 챗봇 서버 연결
  lib/src/screens/home/home.dart
  lib/src/screens/mypage/maincard_manage.dart
  pubspec.yaml
Labels: feature, 해원

#69 [Fix] 마이월렛 카드 이미지 및 요약 뷰 수정
  lib/src/screens/mywallet/card_item.dart
Labels: 지민, fix

#71 [Feat] 마이월렛 카테고리 분류 추가
  lib/src/screens/mywallet/card_item.dart
  lib/src/screens/mywallet/mywallet.dart
Labels: feature, 지민
