Repository EWHA-LUX/ONCE-FE, pull requests merged in 2024-02, with the labels that each got.

#24 [Feature & Style] 전반적인 스타일 수정
  .gitignore
  ios/Runner/AppDelegate.swift
  lib/main.dart
  lib/src/screens/login/login.dart
  lib/src/screens/login/signup1.dart
  lib/src/screens/login/signup2.dart
  lib/src/screens/login/signup3.dart
  lib/src/screens/login/signup4.dart
Labels: feature, 해원, style

#28 [Feature] 내 정보 수정하기 페이지 구현
  lib/src/screens/mypage/user_edit.dart
Labels: feature, 지민

#30 [Feature] 로그인 서버 연결
  lib/main.dart
  lib/src/screens/login/login.dart
  pubspec.yaml
Labels: feature

#32 [Feature] 마이페이지 서버 연결
  lib/src/screens/mypage/mypage.dart
Labels: feature, 해원

#33 [Feature] 주카드 관리 페이지 서버 연결
  lib/src/components/card_list_widget.dart
  lib/src/screens/mypage/maincard_manage.dart
Labels: feature, 해원
