Repository EWHA-LUX/ONCE-FE, pull requests merged in 2024-05, with the labels that each got.

#79 [Fix] 알림 페이지 오류 해결
  lib/src/components/notice_popup_widget.dart
  lib/src/components/notice_widget.dart
Labels: feature, 해원, fix

#81 [Feature] 회원 정보 수정 스낵바 추가
  lib/src/screens/mypage/user_edit.dart
Labels: feature, 해원

#82 [Feature] 주카드 연결 페이지 구현
  assets/images/3d_icons/bulb_3d_icon.svg
  assets/images/3d_icons/rocket_3d_icon.svg
  assets/images/3d_icons/search_3d_icon.png
  assets/images/3d_icons/security_3d_icon.svg
  assets/images/icons/card_company_link_arrow_icon.svg
  assets/images/icons/codef_icon.svg
  assets/images/icons/id_icon.svg
  assets/images/icons/next_icon.png
  assets/images/icons/password_icon.svg
  assets/images/icons/terms_check_icon.svg
  assets/images/icons/terms_check_icon_single.svg
  lib/main.dart
  lib/src/screens/mypage/card_add_method.dart
  lib/src/screens/mypage/codef_terms_conditions.dart
  lib/src/screens/mypage/connect_card_company.dart
  lib/src/screens/mypage/maincard_loading.dart
  lib/src/screens/mypage/maincard_manage.dart
  lib/src/screens/mypage/register_maincard.dart
  lib/src/screens/mypage/register_maincard_list.dart
  lib/src/screens/mypage/search_card1.dart
  lib/src/screens/mypage/search_card2.dart
  pubspec.yaml
Labels: feature, 해원, 지민

#86 [Fix] route 경로 오류 수정
  lib/src/screens/mypage/codef_terms_conditions.dart
  lib/src/screens/mypage/connect_card_company.dart
  lib/src/screens/mypage/maincard_manage.dart
  lib/src/screens/mypage/mypage.dart
  lib/src/screens/mypage/search_card1.dart
Labels: 해원, fix

#87 [Feature] 주카드 아닌 카드실적 입력 구현
  lib/src/screens/mywallet/mywallet.dart
Labels: feature, 지민

#89 [ Fix] 카드명 오버플로우 해결
  lib/src/screens/mypage/maincard_manage.dart
  lib/src/screens/mywallet/mywallet.dart
Labels: 해원, fix

#90 [Feature] 앱 접속 시 주카드 실적 조회 및 기기 토큰 등록 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
  android/build.gradle
  lib/main.dart
  lib/src/screens/login/signup4.dart
  pubspec.yaml
Labels: feature, 지민

#92 [Feature] firebase 연동 의존성 추가
  pubspec.yaml
Labels: feature, 지민

#93 [Feature] 자동로그인 서버 API 연결
  lib/main.dart
Labels: feature, 지민

#95 [Fix] 카드 검색 입력 텍스트 초기화
  lib/src/screens/login/signup4.dart
  lib/src/screens/mypage/search_card2.dart
Labels: 해원, fix

#96 [Feature] 주카드 결제 여부 변경 조건 추가
  lib/src/screens/home/home.dart
  lib/src/screens/mypage/chat_history.dart
Labels: feature, 해원
